sampleData1: |-
    01 09 05 02 27 14   11 12 26 13 19 30
    05 10 01 09 15 29   26 11 12 30 17 08
    04 29 15 10 28 05   11 12 21 17 30 08
                                                        
                                                        
    27 07 03 20 01 09   21 04 08 11 12 26
    27 03 20 13 19 01   28 10 05 11 12 08
    03 13 16 19 20 22   15 10 08 28 05 23
sampleData2: |-
    13 19 30   18 15 05   10 17 33   02 16 22
    04 29 21   01 09 14   31 02 06   18 17 30
    05 06 08   29 30 25   20 28 31   01 02 09
    31 15 20   23 24 07   30 10 05   06 08 09
    02 01 03   12 28 09   30 11 07   24 29 23
    07 18 24   30 10 12   26 13 21   25 31 17
    11 14 16   28 29 24   05 31 06   03 10 08
    04 11 14   16 29 03   23 24 26   33 12 31
sampleData3: |-
    25 06 28 24 33 17   18 29 15 19 09 20
    30 03 31 23 26 27   04 15 19 05 07 11
    30 03 31 26 33 25   32 05 21 12 15 19
                             
    02 27 08 09 14 23   21 29 07 30 32 24
    26 28 27 02 20 03   18 25 14 21 12 09
    02 27 05 28 08 20   11 19 09 32 21 12
                             
    21 30 08 23 22 26   06 27 13 31 05 02
    28 24 30 07 04 27   21 16 02 25 13 20
    30 24 08 28 23 26   15 33 20 05 02 13
                             
    20 05 25 13 02 32   28 21 18 03 07 16
    05 06 07 27 12 28   16 10 31 08 03 24
    05 06 13 20 02 32   07 10 08 16 24 03
                             
    12 20 25 30 01 09   33 05 23 11 19 04
    12 06 13 30 01 10   20 03 07 14 31 21
    12 30 01 13 06 08   14 31 21 33 11 04
                             
    07 17 11 22 31 02   14 18 23 26 03 20
    01 21 32 29 30 07   03 17 22 14 15 23
    07 01 11 09 06 02   20 26 03 05 14 23


setupCode: |-
  def parseData1(input: str) -> tuple[pd.DataFrame]:
      '''
      Parse the input data into a full dataframe and the separated dataframes,
      Named ALL, A, B, C, D
      '''
      df = pd.read_csv(StringIO(input), delim_whitespace=True, header=None)
      # return A,B,C,D dataframes from the full dataframe
      return df, df.iloc[0:3, 0:6], df.iloc[0:3, 6:], df.iloc[3:, 0:6], df.iloc[3:, 6:]

  def parseData2(input: str) -> tuple[pd.DataFrame]:
      '''
      Parse the input data into a full dataframe and the separated dataframes,
      Named ALL, A, B, C, D
      '''
      df = pd.read_csv(StringIO(input), delim_whitespace=True, header=None)
      # return A,B,C,D dataframes from the full dataframe
      return df, df.iloc[:, 0:3], df.iloc[:, 3:6], df.iloc[:, 6:9], df.iloc[:, 9:12]

  def parseData3(input: str) -> tuple[pd.DataFrame]:
      '''
      Parse the input data into a full dataframe and the separated dataframes,
      Named ALL, A, B, C, D, E, F, G, H, I, J, K, L
      '''
      df = pd.read_csv(StringIO(input), delim_whitespace=True, header=None)
      # return A,B,C,D,E,F,G,H,I,J,K,L dataframes from the full dataframe
      return df, df.iloc[0:3, 0:6], df.iloc[3:6, 0:6], df.iloc[6:9, 0:6], df.iloc[9:12, 0:6], df.iloc[12:15, 0:6], df.iloc[15:18, 0:6], df.iloc[0:3, 6:12], df.iloc[3:6, 6:12], df.iloc[6:9, 6:12], df.iloc[9:12, 6:12], df.iloc[12:15, 6:12], df.iloc[15:18, 6:12]


  def dataframeToList(df: pd.DataFrame) -> list:
      '''
      Convert a dataframe to a list
      '''
      # Use a List Comprehension in Python to Flatten Lists of Lists
      return [item for listItem in df.values.tolist() for item in listItem]


  def dataframeToSet(df: pd.DataFrame) -> set:
      '''
      Convert a dataframe to a set
      '''
      return set(dataframeToList(df))


  def seriesToList(series: pd.Series) -> list:
      '''
      Convert a series to a list
      '''
      # Use a List Comprehension in Python to Flatten Lists of Lists
      return [item for item in series.values.tolist()]


  def seriesToSet(series: pd.Series) -> set:
      '''
      Convert a series to a set
      '''
      return set(seriesToList(series))


  def stringifyIterator(data: list[int] | set[int]) -> str:
      '''
      Stringify the iterable data to a space separated string
      '''
      logger.debug(f'data: {data}')
      return ' '.join(map(lambda item: str(item), data))


  def duplicates(data: list) -> set:
      '''
      Find the duplicates in a list, return as a set
      '''
      counts = Counter(data)
      result = [item for item in counts if counts[item] > 1]
      return set(result)


  def occurTimesSet(df: pd.DataFrame, times: int) -> set:
      '''
      Find the elements that occur a given number of times in a dataframe, return as a set
      '''
      counts = Counter(dataframeToList(df))
      result = [item for item in counts if counts[item] == times]
      logger.info(f'counts: {counts}, result: {result}')
      return set(result)


  def occurEqualGreatTimesSet(df: pd.DataFrame, times: int) -> list:
      '''
      Find the elements that occur greater equal then times in a dataframe, return as a set
      '''
      counts = Counter(dataframeToList(df))
      result = [item for item in counts if counts[item] >= times]
      logger.info(f'counts: {counts}, result: {result}')
      return set(result)



OperationCodeBlocks1:
  - name: ASet
    description: A区集合
    code: |-
      ASet = dataframeToSet(A)
  - name: BSet
    description: B区集合
    code: |-
      BSet = dataframeToSet(B)
  - name: ADuplicates
    description: A区集合重复出现数的集合
    code: |-
      ADuplicates = duplicates(dataframeToList(A))
  - name: BDuplicates
    description: B区集合重复出现数的集合
    code: |-
      BDuplicates = duplicates(dataframeToList(B))
  - name: A_BDuplicates
    description: A区B区重复出现数的合集
    code: |-
      A_BDuplicates = ADuplicates | BDuplicates
  - name: CSet
    description: C区集合
    code: |-
      CSet = dataframeToSet(C)
  - name: DSet
    description: D区集合
    code: |-
      DSet = dataframeToSet(D)
  - name: CDuplicates
    description: C区集合重复出现数的集合
    code: |-
      CDuplicates = duplicates(dataframeToList(C))
  - name: DDuplicates
    description: D区集合重复出现数的集合
    code: |-
      DDuplicates = duplicates(dataframeToList(D))
  - name: C_DDuplicates
    description: C区D区重复出现数的合集
    code: |-
      C_DDuplicates = CDuplicates | DDuplicates
  - name: A_CDuplicates
    description: A区C区重复出现数的合集
    code: |-
      A_CDuplicates = ADuplicates | CDuplicates
  - name: B_DDuplicates
    description: B区D区重复出现数的合集
    code: |-
      B_DDuplicates = BDuplicates | DDuplicates
  - name: Row5Set
    description: 第5行集合
    code: |-
      Row5Set = set(seriesToList(ALL.iloc[4,:]))
  - name: A_B_C_DDuplicates
    description: A区B区C区D区重复出现数的合集
    code: |-
      A_B_C_DDuplicates = ADuplicates | BDuplicates | CDuplicates | DDuplicates
  - name: Row1_2_12Set
    description: 第1、2和12列集合
    code: |-
      Row1_2_12Set = dataframeToSet(ALL.iloc[:,[0,1,11]])
  - name: A_B_C_DDuplicatesIntersectRow1_2_12Set
    description: A区B区C区D区重复出现数的合集与第1、2和12列集合的交集
    code: |-
      A_B_C_DDuplicatesIntersectRow1_2_12Set = A_B_C_DDuplicates & Row1_2_12Set
  - name: MissingInAllSet
    description: 数集(1-33)遗漏数集合
    code: |-
      MissingInAllSet = set(range(1,34))-dataframeToSet(ALL)
  - name: OccurOnceSet
    description: 数集中仅出现1次的数的集合
    code: |-
      OccurOnceSet = occurTimesSet(ALL, 1)
  - name: MissingInAllSetIntersectOccurOnceSet
    description: 数集(1-33)遗漏数集合与数集中仅出现1次的数的集合的合集
    code: |-
      MissingInAllSetIntersectOccurOnceSet = MissingInAllSet | OccurOnceSet
  - name: OccurGreate3Set
    description: 数集中出现3次及以上的数的集合
    code: |-
      OccurGreate3Set = occurEqualGreatTimesSet(ALL, 3)
  - name: OccurGreate3Set
    description: 数集(1-33)遗漏数集合与数集中仅出现1次的数的集合的合集 与 数集中出现3次及以上的数的集合 的合集的遗漏数集合
    code: |-
      OccurGreate3Set = set(range(1,34)) - (MissingInAllSetIntersectOccurOnceSet | OccurGreate3Set)
  - name: OccurGreate4Set
    description: 数集中出现4次及以上的数的集合
    code: |-
      OccurGreate4Set = occurEqualGreatTimesSet(ALL, 4)
  - name: ACOccurGreate3Set
    description: AC数集中出现3次及以上的数的集合
    code: |-
      ACOccurGreate3Set = occurEqualGreatTimesSet(ALL.iloc[:,0:6], 3)
      
  - name: ABDuplicates
    description: AB数集中重复出现数的集合
    code: |-
      ABDuplicates = duplicates(dataframeToList(ALL.iloc[0:3,:]))
  - name: MissingInABSet
    description: AB数集中（1-33）遗漏数集合
    code: |-
      MissingInABSet = set(range(1,34)) - dataframeToSet(ALL.iloc[0:3,:])
  - name: OccurOnceInABSet
    description: AB数集中仅出现1次的数的集合
    code: |-
      OccurOnceInABSet = occurTimesSet(ALL.iloc[0:3:,:], 1)
  - name: CDDuplicates
    description: CD数集中重复出现数的集合
    code: |-
      CDDuplicates = duplicates(dataframeToList(ALL.iloc[3:6:,:]))
  - name: MissingInCDSet
    description: CD数集中（1-33）遗漏数集合
    code: |-
      MissingInCDSet = set(range(1,34)) - dataframeToSet(ALL.iloc[3:6:,:])
  - name: OccurOnceInCDSet
    description: CD数集中仅出现1次的数的集合
    code: |-
      OccurOnceInCDSet = occurTimesSet(ALL.iloc[3:6:,:], 1)
  - name: ABDuplicatesUnionCDDuplicates
    description: AB数集中重复出现数的集合 | CD数集中重复出现数的集合
    code: |-
      ABDuplicatesUnionCDDuplicates = ABDuplicates | CDDuplicates
  - name: MissingInAB_CDSet
    description: AB数集中（1-33）遗漏数集合 | CD数集中（1-33）遗漏数集合
    code: |-
      MissingInAB_CDSet = MissingInABSet | MissingInCDSet
  - name: OccurOnceInABCDSet
    description: AB数集中仅出现1次的数的集合 | CD数集中仅出现1次的数的集合
    code: |-
      OccurOnceInABCDSet = OccurOnceInABSet | OccurOnceInCDSet
  - name: ACDuplicates
    description: AC数集中重复出现数的集合
    code: |-
      ACDuplicates = duplicates(dataframeToList(ALL.iloc[:,0:6]))
  - name: MissingInACSet
    description: AC数集中（1-33）遗漏数集合
    code: |-
      MissingInACSet = set(range(1,34)) - dataframeToSet(ALL.iloc[:,0:6])
  - name: OccurOnceInACSet
    description: AC数集中仅出现1次的数的集合
    code: |-
      OccurOnceInACSet = occurTimesSet(ALL.iloc[:,0:6], 1)
  - name: BDDuplicates
    description: BD数集中重复出现数的集合
    code: |-
      BDDuplicates = duplicates(dataframeToList(ALL.iloc[:,6:12]))
  - name: MissingInBDSet
    description: BD数集中（1-33）遗漏数集合
    code: |-
      MissingInBDSet = set(range(1,34)) - dataframeToSet(ALL.iloc[:,6:12])
  - name: OccurOnceInBDSet
    description: BD数集中仅出现1次的数的集合
    code: |-
      OccurOnceInBDSet = occurTimesSet(ALL.iloc[:,6:12], 1)
  - name: ACDuplicatesUnionBDDuplicates
    description: AC数集中重复出现数的集合 | BD数集中重复出现数的集合
    code: |-
      ACDuplicatesUnionBDDuplicates = ACDuplicates | BDDuplicates
  - name: MissingInAC_BDSet
    description: AC数集中（1-33）遗漏数集合 | BD数集中（1-33）遗漏数集合
    code: |-
      MissingInAC_BDSet = MissingInACSet | MissingInBDSet
  - name: OccurOnceInACBDSet
    description: AC数集中仅出现1次的数的集合 | BD数集中仅出现1次的数的集合
    code: |-
      OccurOnceInACBDSet = OccurOnceInACSet | OccurOnceInBDSet
      
  - name: ABCDDuplicatesIntersectACBDDuplicates
    description: ⑦与⑯重复数的集合
    code: |-
      ABCDDuplicatesIntersectACBDDuplicates = ABDuplicatesUnionCDDuplicates & ACDuplicatesUnionBDDuplicates
  - name: MissingInAB_CDSetIntersectMissingInAC_BDSet
    description: ⑧与⑰重复数的集合
    code: |-
      MissingInAB_CDSetIntersectMissingInAC_BDSet = MissingInAB_CDSet & MissingInAC_BDSet
  - name: OccurOnceInABCDSetIntersectOccurOnceInACBDSet
    description: ⑨与⑱重复数的集合
    code: |-
      OccurOnceInABCDSetIntersectOccurOnceInACBDSet = OccurOnceInABCDSet & OccurOnceInACBDSet
  - name: _
    description: ⑦与⑯重复数的集合、⑧与⑰重复数的集合和⑨与⑱重复数的集合（1-33）遗漏数集合
    code: |-
      _ = set(range(1,34)) - (ABCDDuplicatesIntersectACBDDuplicates | MissingInAB_CDSetIntersectMissingInAC_BDSet | OccurOnceInABCDSetIntersectOccurOnceInACBDSet)

OperationCodeBlocks2:
  - name: MissingInABSet
    description: AB数集中（1-33）遗漏数集合
    code: |-
      MissingInABSet = set(range(1,34)) - dataframeToSet(ALL.iloc[:,0:6])
  - name: MissingInCDSet
    description: CD数集中（1-33）遗漏数集合
    code: |-
      MissingInCDSet = set(range(1,34)) - dataframeToSet(ALL.iloc[:,6:12])
  - name: MissingInABSetSymmetricDifferenceMissingInCDSet
    description: AB数集中（1-33）遗漏数集合 与 CD数集中（1-33）遗漏数集合 不同数的集合
    code: |-
      MissingInABSetSymmetricDifferenceMissingInCDSet = MissingInABSet ^ MissingInCDSet
  - name: OccurEqualGreat3TimesInABSet
    description: AB数集中出现3次及以上的数的集合
    code: |-
      OccurEqualGreat3TimesInABSet = occurEqualGreatTimesSet(ALL.iloc[:,0:6], 3)
  - name: OccurEqualGreat3TimesInCDSet
    description: CD数集中出现3次及以上的数的集合
    code: |-
      OccurEqualGreat3TimesInCDSet = occurEqualGreatTimesSet(ALL.iloc[:,6:12], 3)
  - name: OccurEqualGreat3TimesInABSetSymmetricDifferenceOccurEqualGreat3TimesInCDSet
    description: AB数集中出现3次及以上的数的集合 与 CD数集中出现3次及以上的数的集合 不同数的集合
    code: |-
      OccurEqualGreat3TimesInABSetSymmetricDifferenceOccurEqualGreat3TimesInCDSet = OccurEqualGreat3TimesInABSet ^ OccurEqualGreat3TimesInCDSet
      
  - name: ADDuplicatesSet
    description: AD数集中重复出现数的集合
    code: |-
      ADDuplicatesSet = duplicates(dataframeToList(ALL.iloc[:,[0,1,2,9,10,11]]))
  - name: MissingInADSet
    description: AD数集中（1-33）遗漏数集合
    code: |-
      MissingInADSet = set(range(1,34)) - dataframeToSet(ALL.iloc[:,[0,1,2,9,10,11]])
  - name: OccurOnceTimesInADSet
    description: AD数集中出现仅出现1次的数的集合
    code: |-
      OccurOnceTimesInADSet = occurTimesSet(ALL.iloc[:,[0,1,2,9,10,11]], 1)
  - name: ASet
    description: A区集合
    code: |-
      ASet = dataframeToSet(A)
  - name: DSet
    description: D区集合
    code: |-
      DSet = dataframeToSet(D)
  - name: ASetIntersectDSet
    description: A集合 与 D集合 同一数的集合
    code: |-
      ASetIntersectDSet = ASet & DSet
  - name: ASetSymmetricDifference_ASetIntersectDSet
    description: A集合 与 (A集合 与 D集合 同一数的集合) 不同数的集合
    code: |-
      ASetSymmetricDifference_ASetIntersectDSet = ASet ^ ASetIntersectDSet
  - name: DSetSymmetricDifference_ASetIntersectDSet
    description: D集合 与 (A集合 与 D集合 同一数的集合) 不同数的集合
    code: |-
      DSetSymmetricDifference_ASetIntersectDSet = DSet ^ ASetIntersectDSet

  - name: BCDuplicatesSet
    description: BC数集中重复出现数的集合
    code: |-
      BCDuplicatesSet = duplicates(dataframeToList(ALL.iloc[:,3:9]))
  - name: MissingInBCSet
    description: BC数集中（1-33）遗漏数集合
    code: |-
      MissingInBCSet = set(range(1,34)) - dataframeToSet(ALL.iloc[:,3:9])
  - name: OccurOnceTimesInBCSet
    description: BC数集中出现仅出现1次的数的集合
    code: |-
      OccurOnceTimesInBCSet = occurTimesSet(ALL.iloc[:,3:9], 1)
  - name: BSet
    description: B区集合
    code: |-
      BSet = dataframeToSet(B)
  - name: CSet
    description: C区集合
    code: |-
      CSet = dataframeToSet(C)
  - name: BSetIntersectCSet
    description: B集合 与 C集合 同一数的集合
    code: |-
      BSetIntersectCSet = BSet & CSet
  - name: BSetSymmetricDifference_BSetIntersectCSet
    description: B集合 与 (B集合 与 C集合 同一数的集合) 不同数的集合
    code: |-
      BSetSymmetricDifference_BSetIntersectCSet = BSet ^ BSetIntersectCSet
  - name: CSetSymmetricDifference_BSetIntersectCSet
    description: C集合 与 (B集合 与 C集合 同一数的集合) 不同数的集合
    code: |-
      CSetSymmetricDifference_BSetIntersectCSet = CSet ^ BSetIntersectCSet
      
  - name: MissingInADSetUnion_ASetIntersectDSet
    description: AD数集中（1-33）遗漏数集合 与 (A集合 与 D集合 同一数的集合) 的集合
    code: |-
      MissingInADSetUnion_ASetIntersectDSet = MissingInADSet | ASetIntersectDSet
  - name: MissingInBCSetUnion_BSetIntersectCSet
    description: BC数集中（1-33）遗漏数集合 与 (B集合 与 C集合 同一数的集合) 的集合
    code: |-
      MissingInBCSetUnion_BSetIntersectCSet = MissingInBCSet | BSetIntersectCSet
  - name: Data18SymmetricDifference19
    description: 18和19不同数的集合
    code: |-
      Data18SymmetricDifference19 = MissingInADSetUnion_ASetIntersectDSet ^ MissingInBCSetUnion_BSetIntersectCSet
  - name: Data3SymmetricDifference6
    description: 3和6不同数的集合
    code: |-
      Data3SymmetricDifference6 = MissingInABSetSymmetricDifferenceMissingInCDSet ^ OccurEqualGreat3TimesInABSetSymmetricDifferenceOccurEqualGreat3TimesInCDSet

  - name: Data18_19_20_Intersection
    description: 18、19和20出现重复的数的集合
    code: |-
      Data18_19_20_Intersection = duplicates((list(MissingInADSetUnion_ASetIntersectDSet) + list(MissingInBCSetUnion_BSetIntersectCSet) + list(Data3SymmetricDifference6)))
  - name: Data6_12_SymmetricDifference
    description: 6和12不同数的集合
    code: |-
      Data6_12_SymmetricDifference = ADDuplicatesSet ^ BCDuplicatesSet
  - name: Data21_22_SymmetricDifference
    description: 21和22不同数的集合
    code: |-
      Data21_22_SymmetricDifference = Data18_19_20_Intersection ^ Data6_12_SymmetricDifference
  - name: OccurEqualGreat4TimesInABCDSet
    description: ABCD数集中（1-33）遗漏数和出现4次及以上的数的集合
    code: |-
      OccurEqualGreat4TimesInABCDSet = occurEqualGreatTimesSet(ALL, 4)

OperationCodeBlocks3:
  - name: ASet
    description: A区集合
    code: |-
      ASet = dataframeToSet(A)